server:
  port: 8082
  compression:
    enabled: true

mybatis:
  type-aliases-package: org.alige.data.md.model
  mapper-locations: classpath:org.alige.data.md.dao/*.xml
  #executor-type: batch

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/md
    username: postgres
    password: 123456

option_price:
  data:
    dir: D:\BaiduNetdiskDownload\L1_data\option\option_price
    batch_size: 400

option_pricemin:
  data:
    dir: D:\BaiduNetdiskDownload\L1_data\option\option_pricemin
    batch_size: 400

option_price03min:
  data:
    dir: D:\BaiduNetdiskDownload\L1_data\option\option_price03min

option_price05min:
  data:
    dir: D:\BaiduNetdiskDownload\L1_data\option\option_price05min

option_price15min:
  data:
    dir: D:\BaiduNetdiskDownload\L1_data\option\option_price15min

option_price30min:
  data:
    dir: D:\BaiduNetdiskDownload\L1_data\option\option_price30min

option_price60min:
  data:
    dir: D:\BaiduNetdiskDownload\L1_data\option\option_price60min

  logging:
    level:
      org.alige.data.md.dao: info